//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadTestResult.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_LoadTest2010Entities : DbContext
    {
        public db_LoadTest2010Entities()
            : base("name=db_LoadTest2010Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LoadTestBrowser> LoadTestBrowsers { get; set; }
        public DbSet<LoadTestCase> LoadTestCases { get; set; }
        public DbSet<LoadTestDataCollectorLog> LoadTestDataCollectorLogs { get; set; }
        public DbSet<LoadTestDetailMessage> LoadTestDetailMessages { get; set; }
        public DbSet<LoadTestFileAttachment> LoadTestFileAttachments { get; set; }
        public DbSet<LoadTestFileAttachmentChunk> LoadTestFileAttachmentChunks { get; set; }
        public DbSet<LoadTestMessage> LoadTestMessages { get; set; }
        public DbSet<LoadTestMessageType> LoadTestMessageTypes { get; set; }
        public DbSet<LoadTestNetwork> LoadTestNetworks { get; set; }
        public DbSet<LoadTestPageDetail> LoadTestPageDetails { get; set; }
        public DbSet<LoadTestPageSummaryByNetwork> LoadTestPageSummaryByNetworks { get; set; }
        public DbSet<LoadTestPageSummaryData> LoadTestPageSummaryDatas { get; set; }
        public DbSet<LoadTestPerformanceCounter> LoadTestPerformanceCounters { get; set; }
        public DbSet<LoadTestPerformanceCounterCategory> LoadTestPerformanceCounterCategories { get; set; }
        public DbSet<LoadTestPerformanceCounterInstance> LoadTestPerformanceCounterInstances { get; set; }
        public DbSet<LoadTestPerformanceCounterSample> LoadTestPerformanceCounterSamples { get; set; }
        public DbSet<LoadTestReport> LoadTestReports { get; set; }
        public DbSet<LoadTestReportPage> LoadTestReportPages { get; set; }
        public DbSet<LoadTestReportRun> LoadTestReportRuns { get; set; }
        public DbSet<LoadTestRun> LoadTestRuns { get; set; }
        public DbSet<LoadTestRunAgent> LoadTestRunAgents { get; set; }
        public DbSet<LoadTestRunInterval> LoadTestRunIntervals { get; set; }
        public DbSet<LoadTestScenario> LoadTestScenarios { get; set; }
        public DbSet<LoadTestSchemaRevision> LoadTestSchemaRevisions { get; set; }
        public DbSet<LoadTestSqlTrace> LoadTestSqlTraces { get; set; }
        public DbSet<LoadTestSystemUnderTest> LoadTestSystemUnderTests { get; set; }
        public DbSet<LoadTestSystemUnderTestTag> LoadTestSystemUnderTestTags { get; set; }
        public DbSet<LoadTestTestDetail> LoadTestTestDetails { get; set; }
        public DbSet<LoadTestTestLog> LoadTestTestLogs { get; set; }
        public DbSet<LoadTestTestSummaryData> LoadTestTestSummaryDatas { get; set; }
        public DbSet<LoadTestThresholdMessage> LoadTestThresholdMessages { get; set; }
        public DbSet<LoadTestTransactionDetail> LoadTestTransactionDetails { get; set; }
        public DbSet<LoadTestTransactionSummaryData> LoadTestTransactionSummaryDatas { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<WebLoadTestErrorDetail> WebLoadTestErrorDetails { get; set; }
        public DbSet<WebLoadTestRequestMap> WebLoadTestRequestMaps { get; set; }
        public DbSet<WebLoadTestTransaction> WebLoadTestTransactions { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
